### ISSUE TITLE
Binwalk v3 doesn't recognize signature unlike v2

### ISSUE THREAD

**Issue by dryBoneMarrow** [ReFirmLabs/binwalk#750] opened 2024-11-18 15:25 UTC
Binwalk v2 used to recognize files embedded into an image file (from a [ctf](https://library.m0unt41n.ch/challenges/imagine)) whereas v3 does not. The file is a jpg file, the embedded files are also jpg's and an invalid tiff.

File in question:
```
$ file ultimate-meme.jpg
ultimate-meme.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=8, description=Created with GIMP, orientation=upper-left, xresolution=128, yresolution=136, resolutionunit=2, software=GIMP 2.10.38, datetime=2024:09:16 19:51:13], comment: "Created with GIMP", progressive, precision 8, 881x500, components 3
```
Extracted files using binwalk v2:
```
$ file _ultimate-meme.jpg.extracted/*
_ultimate-meme.jpg.extracted/0:     JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=8, description=Created with GIMP, orientation=upper-left, xresolution=128, yresolution=136, resolutionunit=2, software=GIMP 2.10.38, datetime=2024:09:16 19:51:13], comment: "Created with GIMP", progressive, precision 8, 881x500, components 3
_ultimate-meme.jpg.extracted/15BBE: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, comment: "Created with GIMP", progressive, precision 8, 500x60, components 3
_ultimate-meme.jpg.extracted/1E:    TIFF image data, little-endian, direntries=8, description=Created with GIMP, orientation=upper-left, xresolution=128, yresolution=136, resolutionunit=2, software=GIMP 2.10.38, datetime=2024:09:16 19:51:13
```
The jpg inclusive the extracted files are appended
[image.tar.gz](https://github.com/user-attachments/files/17802587/image.tar.gz)

**Comment by devttys0** [comment] 2024-11-20 16:05
This was caused by the fact that end-of-file detection for JPEGs was rudimentary at best. Just merged a patch into the master branch to fix this:

![image](https://github.com/user-attachments/assets/7ab09248-4626-498d-b31d-dc199e9c8685)

**Closed by devttys0** 2024-11-20 16:05 UTC
